---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: StorageGRID 11.8 verwendet Version 4 der Mandantenmanagement-API. Version 4 verfällt Version 3; allerdings werden die Versionen 1, 2 und 3 weiterhin unterstützt. 
---
= Änderungen an der Mandantenmanagement-API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.8 verwendet Version 4 der Mandantenmanagement-API. Version 4 verfällt Version 3; allerdings werden die Versionen 1, 2 und 3 weiterhin unterstützt.


NOTE: Sie können weiterhin veraltete Versionen der Mandantenmanagement-API mit StorageGRID 11.8 verwenden. Die Unterstützung für diese Versionen der API wird jedoch in einer zukünftigen Version von StorageGRID entfernt. Nach dem Upgrade auf StorageGRID 11.8 können die veralteten APIs mit dem deaktiviert werden `PUT /grid/config/management` API:

Weitere Informationen finden Sie unter link:../tenant/understanding-tenant-management-api.html["Mandantenmanagement-API verstehen"].



== Neue Endpunkte für ILM-Richtlinien-Tags

Sie können die API-Endpunkte */org/ilm-Policy-Tags* und */org/Containers/{bucketName}/ilm-Policy-Tags* verwenden, um Vorgänge im Zusammenhang mit ILM-Richtlinien-Tags durchzuführen.
