---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: Bevor Sie mit dem Upgrade beginnen, überprüfen Sie, ob die vorherige Version von StorageGRID derzeit mit dem neuesten verfügbaren Hotfix installiert ist. 
---
= Überprüfen Sie die installierte StorageGRID-Version
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie mit dem Upgrade beginnen, überprüfen Sie, ob die vorherige Version von StorageGRID derzeit mit dem neuesten verfügbaren Hotfix installiert ist.

.Über diese Aufgabe
Vor dem Upgrade auf StorageGRID 11.8 muss StorageGRID 11.7 auf Ihrem Grid installiert sein. Wenn Sie derzeit eine frühere Version von StorageGRID verwenden, müssen Sie alle vorherigen Aktualisierungsdateien zusammen mit den neuesten Hotfixes installieren (dringend empfohlen), bis die aktuelle Version Ihres Grids StorageGRID 11.7 ist._x.y_.

Ein möglicher Upgrade-Pfad wird im angezeigt <<Beispiel: Upgrade auf StorageGRID 11.7 von Version 11.5,Beispiel>>.


CAUTION: NetApp empfiehlt dringend, vor dem Upgrade auf die nächste Version den aktuellen Hotfix für jede StorageGRID-Version anzuwenden und den aktuellen Hotfix für jede installierte neue Version anzuwenden. In einigen Fällen müssen Sie einen Hotfix anwenden, um das Risiko eines Datenverlusts zu vermeiden. Siehe https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^] Und die Release Notes für jeden Hotfix, um mehr zu erfahren.

.Schritte
. Melden Sie sich mit einem bei Grid Manager an link:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
. Wählen Sie oben im Grid Manager die Option *Hilfe* > *Info*.
. Stellen Sie sicher, dass *Version* 11.7._x.y_ ist.
+
In der StorageGRID 11.7._x.y_ Versionsnummer:

+
** Das *Major Release* hat einen _x_ Wert von 0 (11.7.0).
** Ein *Hotfix* hat, wenn man angewendet wurde, einen _y_ Wert (z.B. 11.7.0.1).


. Wenn *Version* nicht 11.7._x.y_ ist, gehen Sie zu https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^] So laden Sie die Dateien für jede vorherige Version herunter, einschließlich des neuesten Hotfix für jede Version.
. Lesen Sie die Upgrade-Anweisungen für jede heruntergeladene Version. Führen Sie dann das Software-Upgrade-Verfahren für dieses Release durch, und wenden Sie den neuesten Hotfix für dieses Release an (dringend empfohlen).
+
Siehe link:../maintain/storagegrid-hotfix-procedure.html["StorageGRID Hotfix Verfahren"].





== Beispiel: Upgrade auf StorageGRID 11.7 von Version 11.5

Das folgende Beispiel zeigt die Schritte zum Upgrade von StorageGRID Version 11.5 auf Version 11.7 als Vorbereitung auf ein StorageGRID 11.8-Upgrade.

Laden Sie die Software in der folgenden Reihenfolge herunter und installieren Sie sie, um Ihr System auf die Aktualisierung vorzubereiten:

. Wenden Sie den aktuellen StorageGRID 11.5.0._y_ Hotfix an.
. Upgrade auf die Hauptversion von StorageGRID 11.6.0.
. Wenden Sie den aktuellen StorageGRID 11.6.0._y_ Hotfix an.
. Upgrade auf die Hauptversion von StorageGRID 11.7.0.
. Wenden Sie den aktuellen StorageGRID 11.7.0._y_ Hotfix an.

