---
permalink: swift/swift-rest-api-supported-operations.html 
sidebar: sidebar 
keywords: OpenStack, Swift API, REST API 
summary: Das StorageGRID System unterstützt die meisten Operationen in der OpenStack Swift API. Informieren Sie sich vor der Integration von Swift REST API Clients mit StorageGRID über die Implementierungsdetails für Konto-, Container- und Objektvorgänge. 
---
= Von Swift UNTERSTÜTZTE REST-API-Operationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das StorageGRID System unterstützt die meisten Operationen in der OpenStack Swift API. Informieren Sie sich vor der Integration von Swift REST API Clients mit StorageGRID über die Implementierungsdetails für Konto-, Container- und Objektvorgänge.



== Von StorageGRID unterstützte Vorgänge

Die folgenden Swift-API-Operationen werden unterstützt:

* link:account-operations.html["Konto-Operationen"]
* link:container-operations.html["Container-Operationen"]
* link:object-operations.html["Objekt-Operationen"]




== Gemeinsame Antwortheader für alle Vorgänge

Das StorageGRID-System implementiert alle gemeinsamen Header für unterstützte Vorgänge, wie sie von der OpenStack Swift Objekt-Storage-API v1 definiert wurden.

.Verwandte Informationen
http://docs.openstack.org/developer/swift/api/object_api_v1_overview.html["OpenStack: Objekt-Storage-API"^]
