= Suchen Sie nach Hostnamen für Speicherknoten
:allow-uri-read: 




== Suchen Sie nach Hostnamen für Speicherknoten

. Melden Sie sich beim primären Admin-Node an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_primary_Admin_Node_IP_`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
.. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
+
Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.



. Verwenden Sie die `/etc/hosts` Datei, um den Hostnamen des Speicher-Knotens für die wiederhergestellten Speicher-Volumes zu finden. Um eine Liste aller Nodes im Raster anzuzeigen, geben Sie Folgendes ein: `cat /etc/hosts`.




== Reparieren Sie Daten, wenn alle Volumes ausgefallen sind

Wenn alle Storage-Volumes ausgefallen sind, reparieren Sie den gesamten Node. Befolgen Sie die Anweisungen für *replizierte Daten*, *Erasure-codierte (EC) Daten* oder beide, je nachdem, ob Sie replizierte Daten, Erasure-codierte (EC) Daten oder beide verwenden.

Wenn nur einige Volumes gescheitert sind, gehen Sie zu <<Reparieren Sie Daten, wenn nur einige Volumes ausgefallen sind>>.


NOTE: Du kannst nicht laufen `repair-data` Betrieb für mehr als einen Node gleichzeitig. Wenden Sie sich an den technischen Support, um mehrere Nodes wiederherzustellen.

[role="tabbed-block"]
====
.Replizierte Daten
--
Wenn in Ihrem Grid replizierte Daten enthalten sind, verwenden Sie das `repair-data start-replicated-node-repair` Befehl mit dem `--nodes` Option, wo `--nodes` Ist der Hostname (Systemname), um den gesamten Speicher-Node zu reparieren.

Mit diesem Befehl werden die replizierten Daten auf einem Storage-Node mit dem Namen SG-DC-SN3 repariert:

`repair-data start-replicated-node-repair --nodes SG-DC-SN3`


NOTE: Bei der Wiederherstellung von Objektdaten wird die Warnmeldung *Objektverlust* ausgelöst, wenn das StorageGRID-System keine replizierten Objektdaten finden kann. Auf Storage-Nodes im gesamten System können Warnmeldungen ausgelöst werden. Sie sollten die Ursache des Schadens bestimmen und feststellen, ob eine Wiederherstellung möglich ist. Siehe link:../troubleshoot/investigating-lost-objects.html["Untersuchen Sie verlorene Objekte"].

--
.EC-Daten (Erasure Coded)
--
Wenn in Ihrem Grid Daten zur Einhaltung von Datenkonsistenz (Erasure Coding) enthalten sind, verwenden Sie den `repair-data start-ec-node-repair` Befehl mit dem `--nodes` Option, wo `--nodes` Ist der Hostname (Systemname), um den gesamten Speicher-Node zu reparieren.

Mit diesem Befehl werden die Erasure-codierten Daten auf einem Storage-Node mit dem Namen SG-DC-SN3 repariert:

`repair-data start-ec-node-repair --nodes SG-DC-SN3`

Der Vorgang gibt einen eindeutigen zurück `repair ID` Das identifiziert dies `repair_data` Betrieb. Verwenden Sie diese Option `repair ID` Den Fortschritt und das Ergebnis des verfolgen `repair_data` Betrieb. Beim Abschluss des Wiederherstellungsprozesses wird kein weiteres Feedback zurückgegeben.


NOTE: Reparaturen von Daten, die auf Löschung codiert wurden, können beginnen, während einige Storage-Nodes offline sind. Die Reparatur ist abgeschlossen, wenn alle Nodes verfügbar sind.

--
====


== Reparieren Sie Daten, wenn nur einige Volumes ausgefallen sind

Wenn nur einige Volumes ausgefallen sind, die betroffenen Volumes reparieren. Befolgen Sie die Anweisungen für *replizierte Daten*, *Erasure-codierte (EC) Daten* oder beide, je nachdem, ob Sie replizierte Daten, Erasure-codierte (EC) Daten oder beide verwenden.

Wenn alle Volumes ausgefallen sind, gehen Sie zu <<Reparieren Sie Daten, wenn alle Volumes ausgefallen sind>>.

Geben Sie die Volume-IDs in hexadezimal ein. Beispiel: `0000` Ist der erste Band und `000F` Ist der sechzehnte Band. Sie können ein Volume, einen Bereich von Volumes oder mehrere Volumes angeben, die sich nicht in einer Sequenz befinden.

Alle Volumes müssen sich auf demselben Speicherknoten befinden. Wenn Sie Volumes für mehr als einen Speicherknoten wiederherstellen müssen, wenden Sie sich an den technischen Support.

[role="tabbed-block"]
====
.Replizierte Daten
--
Wenn Ihr Grid replizierte Daten enthält, verwenden Sie das `start-replicated-volume-repair` Befehl mit dem `--nodes` Option zum Identifizieren des Knotens (wobei `--nodes` Ist der Hostname des Node). Fügen Sie dann entweder die hinzu `--volumes` Oder `--volume-range` Option, wie in den folgenden Beispielen dargestellt.

*Einzelnes Volume*: Dieser Befehl stellt replizierte Daten auf das Volume wieder her `0002` Auf einem Storage-Node mit dem Namen SG-DC-SN3:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0002`

*Bereich von Volumes*: Dieser Befehl stellt replizierte Daten auf alle Volumes im Bereich wieder her `0003` Bis `0009` Auf einem Storage-Node mit dem Namen SG-DC-SN3:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

*Mehrere Volumes nicht in einer Sequenz*: Dieser Befehl stellt replizierte Daten in Volumes wieder her `0001`, `0005`, und `0008` Auf einem Storage-Node mit dem Namen SG-DC-SN3:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0001,0005,0008`


NOTE: Bei der Wiederherstellung von Objektdaten wird die Warnmeldung *Objektverlust* ausgelöst, wenn das StorageGRID-System keine replizierten Objektdaten finden kann. Auf Storage-Nodes im gesamten System können Warnmeldungen ausgelöst werden. Notieren Sie sich die Beschreibung der Warnmeldung und die empfohlenen Maßnahmen, um die Ursache des Verlusts zu ermitteln und zu ermitteln, ob eine Wiederherstellung möglich ist.

--
.EC-Daten (Erasure Coded)
--
Wenn in Ihrem Grid Daten zur Einhaltung von Datenkonsistenz (Erasure Coding) enthalten sind, verwenden Sie den `start-ec-volume-repair` Befehl mit dem `--nodes` Option zum Identifizieren des Knotens (wobei `--nodes` Ist der Hostname des Node). Fügen Sie dann entweder die hinzu `--volumes` Oder `--volume-range` Option, wie in den folgenden Beispielen dargestellt.

*Einzelnes Volume*: Dieser Befehl stellt die mit dem Löschen kodierten Daten auf das Volume wieder her `0007` Auf einem Storage-Node mit dem Namen SG-DC-SN3:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 0007`

*Bereich von Volumes*: Dieser Befehl stellt Daten mit Löschungscode auf alle Volumes im Bereich wieder her `0004` Bis `0006` Auf einem Storage-Node mit dem Namen SG-DC-SN3:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

*Mehrere Volumes nicht in einer Sequenz*: Dieser Befehl stellt Erasure-codierte Daten auf Volumes wieder her `000A`, `000C`, und `000E` Auf einem Storage-Node mit dem Namen SG-DC-SN3:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 000A,000C,000E`

Der `repair-data` Der Vorgang gibt einen eindeutigen zurück `repair ID` Das identifiziert dies `repair_data` Betrieb. Verwenden Sie diese Option `repair ID` Den Fortschritt und das Ergebnis des verfolgen `repair_data` Betrieb. Beim Abschluss des Wiederherstellungsprozesses wird kein weiteres Feedback zurückgegeben.


NOTE: Reparaturen von Daten, die auf Löschung codiert wurden, können beginnen, während einige Storage-Nodes offline sind. Die Reparatur ist abgeschlossen, wenn alle Nodes verfügbar sind.

--
====