---
permalink: tenant/configuration-xml-for-search-configuration.html 
sidebar: sidebar 
keywords: search integration, configuration xml, metadata notification, container tag, urn 
summary: Der Such-Integrationsservice wird anhand einer Reihe von Regeln konfiguriert, die in <MetadataNotificationConfiguration\> und </MetadataNotificationConfiguration\> Tags enthalten sind. Jede Regel gibt die Objekte an, für die die Regel gilt, und das Ziel, an dem StorageGRID die Metadaten dieser Objekte senden soll. 
---
= Konfigurations-XML für die Integration der Suche
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Such-Integrationsservice wird anhand einer Reihe von Regeln konfiguriert, die in enthalten sind `<MetadataNotificationConfiguration>` Und `</MetadataNotificationConfiguration>` tags: Jede Regel gibt die Objekte an, auf die sich die Regel bezieht, und das Ziel, an dem StorageGRID die Metadaten dieser Objekte senden sollte.

Objekte können nach dem Präfix des Objektnamens gefiltert werden. Beispielsweise können Sie Metadaten für Objekte mit dem Präfix senden `images` An ein Ziel und die Metadaten für Objekte mit dem Präfix `videos` Nach anderen. Konfigurationen mit überlappenden Präfixen sind nicht gültig und werden beim Einreichen abgelehnt. Beispiel: Eine Konfiguration, die eine Regel für Objekte mit dem Präfix enthält `test` Und eine zweite Regel für Objekte mit dem Präfix `test2` Ist nicht zulässig.

Ziele müssen mit dem URN eines StorageGRID-Endpunkts angegeben werden, der für den Suchintegrationsdienst erstellt wurde. Diese Endpunkte beziehen sich auf einen Index und einen Typ, der in einem Elasticsearch-Cluster definiert ist.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
In der Tabelle werden die Elemente in der XML-Konfiguration für die Metadatenbenachrichtigung beschrieben.

[cols="2a,3a,1a"]
|===
| Name | Beschreibung | Erforderlich 


 a| 
MetadataNotificationKonfiguration
 a| 
Container-Tag für Regeln zur Angabe von Objekten und Zielen für Metadatenbenachrichtigungen

Enthält mindestens ein Regelelement.
 a| 
Ja.



 a| 
Regel
 a| 
Container-Tag für eine Regel, die die Objekte identifiziert, deren Metadaten zu einem bestimmten Index hinzugefügt werden sollen.

Regeln mit überlappenden Präfixen werden abgelehnt.

Im MetadataNotificationConfiguration Element enthalten.
 a| 
Ja.



 a| 
ID
 a| 
Eindeutige Kennung für die Regel.

In das Element Regel aufgenommen.
 a| 
Nein



 a| 
Status
 a| 
Der Status kann „aktiviert“ oder „deaktiviert“ sein. Für deaktivierte Regeln wird keine Aktion durchgeführt.

In das Element Regel aufgenommen.
 a| 
Ja.



 a| 
Präfix
 a| 
Objekte, die mit dem Präfix übereinstimmen, werden von der Regel beeinflusst und ihre Metadaten werden an das angegebene Ziel gesendet.

Geben Sie ein leeres Präfix an, um alle Objekte zu entsprechen.

In das Element Regel aufgenommen.
 a| 
Ja.



 a| 
Ziel
 a| 
Container-Tag für das Ziel einer Regel.

In das Element Regel aufgenommen.
 a| 
Ja.



 a| 
Urne
 a| 
URNE des Ziels, an dem Objektmetadaten gesendet werden. Muss der URN eines StorageGRID-Endpunkts mit den folgenden Eigenschaften sein:

* `es` Muss das dritte Element sein.
* Der URN muss mit dem Index und dem Typ enden, in dem die Metadaten gespeichert werden, im Formular `domain-name/myindex/mytype`.


Endpunkte werden mithilfe der Mandanten-Manager oder der Mandanten-Management-API konfiguriert. Sie nehmen folgende Form:

* `arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


Der Endpunkt muss konfiguriert werden, bevor die Konfigurations-XML gesendet wird, oder die Konfiguration schlägt mit einem Fehler 404 fehl.

URNE ist im Element Ziel enthalten.
 a| 
Ja.

|===
Verwenden Sie die XML-XML-Beispielkonfiguration für Metadatenbenachrichtigungen, um zu erfahren, wie Sie Ihre eigene XML erstellen.



== Konfiguration der Metadatenbenachrichtigung für alle Objekte

In diesem Beispiel werden die Objektmetadaten für alle Objekte an dasselbe Ziel gesendet.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix></Prefix>
        <Destination>
           <Urn>urn:myes:es:::sgws-notifications/test1/all</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----


== Konfiguration der Metadatenbenachrichtigung mit zwei Regeln

In diesem Beispiel sind die Objektmetadaten für Objekte mit dem Präfix übereinstimmen `/images` An ein Ziel gesendet wird, während die Objektmetadaten für Objekte mit dem Präfix übereinstimmen `/videos` Wird an ein zweites Ziel gesendet.

[listing]
----

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Images-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/images</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/es-domain/graphics/imagetype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Videos-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/videos</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-west-1:22222222:domain/es-domain/graphics/videotype</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.Verwandte Informationen
link:../s3/index.html["S3-REST-API VERWENDEN"]

link:object-metadata-included-in-metadata-notifications.html["Objektmetadaten sind in Metadaten-Benachrichtigungen enthalten"]

link:json-generated-by-search-integration-service.html["JSON durch den Suchintegrations-Service generiert"]

link:configuring-search-integration-service.html["Konfigurieren Sie den Suchintegrationsdienst"]
