---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: 'Ein Mandantenkonto ermöglicht Ihnen, entweder die Simple Storage Service (S3) REST-API oder die Swift REST-API zu verwenden, um Objekte in einem StorageGRID System zu speichern und abzurufen.' 
---
= Verwenden Sie ein Mandantenkonto: Überblick
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Mandantenkonto ermöglicht Ihnen, entweder die Simple Storage Service (S3) REST-API oder die Swift REST-API zu verwenden, um Objekte in einem StorageGRID System zu speichern und abzurufen.



== Was ist ein Mandantenkonto?

Jedes Mandantenkonto verfügt über eigene föderierte bzw. lokale Gruppen, Benutzer, S3 Buckets oder Swift Container und Objekte.

Mandantenkonten können verwendet werden, um gespeicherte Objekte durch verschiedene Einheiten zu trennen. Beispielsweise können für einen der folgenden Anwendungsfälle mehrere Mandantenkonten verwendet werden:

* *Anwendungsbeispiel für Unternehmen:* Wenn das StorageGRID-System innerhalb eines Unternehmens verwendet wird, kann der Objekt-Storage des Grid von den verschiedenen Abteilungen des Unternehmens getrennt werden. Beispielsweise können Mandantenkonten für die Marketingabteilung, die Kundenbetreuung, die Personalabteilung usw. vorhanden sein.
+

NOTE: Wenn Sie das S3-Client-Protokoll verwenden, können Sie auch S3-Buckets und Bucket-Richtlinien verwenden, um Objekte zwischen den Abteilungen eines Unternehmens zu trennen. Sie müssen keine separaten Mandantenkonten erstellen. Siehe Anweisungen zur Implementierung link:../s3/bucket-and-group-access-policies.html["S3-Buckets und Bucket-Richtlinien"] Finden Sie weitere Informationen.

* *Anwendungsfall des Service-Providers:* Wenn das StorageGRID-System von einem Service-Provider verwendet wird, kann der Objekt-Storage des Grid von den verschiedenen Einheiten getrennt werden, die den Storage leasen. Beispielsweise können Mandantenkonten für Unternehmen A, Unternehmen B, Unternehmen C usw. vorhanden sein.




== Erstellen eines Mandantenkontos

Mandantenkonten werden von einem erstellt link:../admin/managing-tenants.html["StorageGRID Grid-Administrator, der den Grid Manager verwendet"]. Beim Erstellen eines Mandantenkontos gibt der Grid-Administrator Folgendes an:

* Grundlegende Informationen, einschließlich Mandantenname, Client-Typ (S3 oder Swift) und optionalem Storage-Kontingent.
* Berechtigungen für das Mandantenkonto, z. B. ob das Mandantenkonto S3-Plattformservices verwenden, seine eigene Identitätsquelle konfigurieren, S3 Select verwenden oder eine Grid-Verbundverbindung verwenden kann.
* Der erste Root-Zugriff für den Mandanten basiert darauf, ob das StorageGRID System lokale Gruppen und Benutzer, Identitätsföderation oder Single Sign On (SSO) verwendet.


Grid-Administratoren können zudem die S3-Objektsperreneinstellung für das StorageGRID System aktivieren, wenn S3-Mandantenkonten die gesetzlichen Anforderungen erfüllen müssen. Wenn S3 Object Lock aktiviert ist, können alle S3-Mandantenkonten konforme Buckets erstellen und managen.



=== S3-Mandanten konfigurieren

Nach einem link:../admin/creating-tenant-account.html["S3-Mandantenkonto wird erstellt"], Sie können auf den Tenant Manager zugreifen, um Aufgaben wie die folgenden durchzuführen:

* Identitätsföderation einrichten (es sei denn, die Identitätsquelle wird mit dem Grid gemeinsam genutzt)
* Verwalten von Gruppen und Benutzern
* Grid-Verbund für Account-Klone und Grid-übergreifende Replizierung verwenden
* Managen von S3-Zugriffsschlüsseln
* S3 Buckets erstellen und managen
* Verwenden Sie S3-Plattformservices
* Verwenden Sie S3 Select
* Monitoring der Storage-Auslastung



TIP: Sie können S3-Buckets zwar mit dem Tenant Manager erstellen und managen, Sie müssen jedoch ein verwenden link:../s3/index.html["S3-Client"] Oder link:use-s3-console.html["S3-Konsole"] Zum Einspielen und Verwalten von Objekten.



=== Konfigurieren Sie Swift Mandanten

Nach A link:../admin/creating-tenant-account.html["Swift-Mandantenkonto wird erstellt"], Sie können auf den Tenant Manager zugreifen, um Aufgaben wie die folgenden durchzuführen:

* Identitätsföderation einrichten (es sei denn, die Identitätsquelle wird mit dem Grid gemeinsam genutzt)
* Verwalten von Gruppen und Benutzern
* Monitoring der Storage-Auslastung



TIP: Swift-Benutzer müssen über die Root-Zugriffsberechtigung für den Zugriff auf den Mandanten-Manager verfügen. Die Root-Zugriffsberechtigung erlaubt Benutzern jedoch nicht, sich beim zu authentifizieren link:../swift/index.html["Swift REST API"] Um Container zu erstellen und Objekte aufzunehmen. Benutzer müssen über die Swift-Administratorberechtigung verfügen, um sich bei der Swift-REST-API zu authentifizieren.
