---
permalink: tenant/understanding-notifications-for-buckets.html 
sidebar: sidebar 
keywords: s3 bucket event notification, sequencer key 
summary: Sie können die Ereignisbenachrichtigung für einen S3-Bucket aktivieren, wenn StorageGRID Benachrichtigungen über angegebene Ereignisse an ein Kafka-Zielcluster oder Amazon Simple Notification Service senden soll. 
---
= Informieren Sie sich über Benachrichtigungen für Buckets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Ereignisbenachrichtigung für einen S3-Bucket aktivieren, wenn StorageGRID Benachrichtigungen über angegebene Ereignisse an ein Kafka-Zielcluster oder Amazon Simple Notification Service senden soll.

Das können Sie link:configuring-event-notifications.html["Konfigurieren Sie Ereignisbenachrichtigungen"] Durch Verknüpfung von XML für die Benachrichtigungskonfiguration mit einem Quell-Bucket. Die XML-Benachrichtigungskonfiguration folgt S3-Konventionen für die Konfiguration von Bucket-Benachrichtigungen. Das Ziel-Kafka- oder Amazon SNS-Thema wird als URN eines Endpunkts angegeben.

Ereignisbenachrichtigungen werden auf dem Quell-Bucket erstellt, wie in der Benachrichtigungskonfiguration angegeben, und werden an das Ziel übergeben. Wenn ein Ereignis, das einem Objekt zugeordnet ist, erfolgreich ist, wird eine Benachrichtigung über dieses Ereignis erstellt und für die Bereitstellung in die Warteschlange verschoben.

Die Eindeutigkeit und Bestellung von Benachrichtigungen ist nicht garantiert. Möglicherweise werden mehrere Benachrichtigungen zu einem Ereignis an das Ziel übermittelt, da die Maßnahmen zur Sicherstellung des Liefererfolgs durchgeführt werden. Da die Bereitstellung asynchron ist, entspricht die Reihenfolge der Benachrichtigungen am Ziel nicht der Reihenfolge der Ereignisse auf dem Quell-Bucket. Dies gilt insbesondere für Vorgänge, die von unterschiedlichen StorageGRID-Standorten stammen. Sie können das verwenden `sequencer` Schlüssel in der Ereignismeldung, um die Reihenfolge der Ereignisse für ein bestimmtes Objekt zu bestimmen, wie in der Amazon S3-Dokumentation beschrieben.



== Unterstützte Benachrichtigungen und Meldungen

StorageGRID-Ereignisbenachrichtigungen folgen der Amazon S3-API mit einigen Einschränkungen:

* Die folgenden Ereignistypen werden unterstützt:
+
** s3:ObjectCreated:*
** s3:ObjectCreated:Put
** s3:ObjectCreated:Post
** s3:ObjectCreated:Copy
** s3:ObjectCreated:CompleteMultipartUpload
** s3:ObjectRemoved:*
** s3:ObjectRemoved:Löschen
** s3:ObjectRemoved:DeleteMarkerCreated
** s3:ObjectRestore:Post


* Aus StorageGRID gesendete Ereignisbenachrichtigungen verwenden das Standard-JSON-Format, enthalten aber keine Schlüssel und verwenden bestimmte Werte für andere, wie in der Tabelle gezeigt:


[cols="1a,2a"]
|===
| Schlüsselname | Wert von StorageGRID 


 a| 
EventSource
 a| 
`sgws:s3`



 a| 
AwsRegion
 a| 
Nicht enthalten



 a| 
X-amz-id-2
 a| 
Nicht enthalten



 a| 
arn
 a| 
`urn:sgws:s3:::bucket_name`

|===