---
permalink: tenant/viewing-your-s3-access-keys.html 
sidebar: sidebar 
keywords: how to view your s3 access key 
summary: Wenn Sie einen S3-Mandanten verwenden und über die entsprechenden Berechtigungen verfügen, können Sie eine Liste Ihrer S3-Zugriffsschlüssel anzeigen. Sie können die Liste nach Ablauf der Zeit sortieren, sodass Sie feststellen können, welche Schlüssel bald ablaufen. Nach Bedarf können Sie neue Schlüssel erstellen oder Schlüssel löschen, die Sie nicht mehr verwenden. 
---
= Die S3-Zugriffsschlüssel anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen S3-Mandanten verwenden und über die verfügen link:tenant-management-permissions.html["Entsprechende Berechtigung"], Sie können eine Liste Ihrer S3-Zugriffsschlüssel anzeigen. Sie können die Liste nach Ablauf der Zeit sortieren, sodass Sie feststellen können, welche Schlüssel bald ablaufen. Nach Bedarf können Sie link:creating-your-own-s3-access-keys.html["Erstellen Sie neue Schlüssel"] Oder link:deleting-your-own-s3-access-keys.html["Schlüssel löschen"] Die Sie nicht mehr verwenden.


CAUTION: Sie können auf die S3-Buckets und Objekte aus Ihrem Konto zugreifen, indem Sie die Zugriffsschlüssel-ID und den geheimen Zugriffsschlüssel verwenden, die für Ihr Konto im Mandanten-Manager angezeigt werden. Aus diesem Grund schützen Sie Zugriffsschlüssel wie ein Passwort. Drehen Sie regelmäßig Zugriffsschlüssel, entfernen Sie alle nicht verwendeten Schlüssel aus Ihrem Konto und teilen Sie sie niemals mit anderen Benutzern.

.Bevor Sie beginnen
* Sie sind mit einem beim Mandantenmanager angemeldet link:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie gehören einer Benutzergruppe an, die über die eigenen S3-Anmeldeinformationen verwalten verfügt link:tenant-management-permissions.html["Berechtigung"].


.Schritte
. Wählen Sie *STORAGE (S3)* > *Meine Zugriffsschlüssel* aus.
. Sortieren Sie auf der Seite Meine Zugriffsschlüssel alle vorhandenen Zugriffsschlüssel nach *Ablaufzeit* oder *Zugriffsschlüssel-ID*.
. Erstellen Sie nach Bedarf neue Schlüssel oder löschen Sie alle Schlüssel, die Sie nicht mehr verwenden.
+
Wenn Sie neue Schlüssel erstellen, bevor die vorhandenen Schlüssel ablaufen, können Sie mit der Verwendung der neuen Schlüssel beginnen, ohne vorübergehend den Zugriff auf die Objekte im Konto zu verlieren.

+
Abgelaufene Schlüssel werden automatisch entfernt.


