---
permalink: tenant/viewing-s3-bucket-details.html 
sidebar: sidebar 
keywords: how to view bucket details 
summary: Sie können die Buckets in Ihrem Mandantenkonto anzeigen. 
---
= Bucket-Details anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Buckets in Ihrem Mandantenkonto anzeigen.

.Bevor Sie beginnen
* Sie sind mit einem beim Mandantenmanager angemeldet link:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie gehören einer Benutzergruppe an, die über den verfügt link:tenant-management-permissions.html["Root-Zugriff, Alle Buckets verwalten oder Alle Buckets anzeigen"]. Diese Berechtigungen überschreiben die Berechtigungseinstellungen in Gruppen- oder Bucket-Richtlinien.


.Schritte
. Wählen Sie *View Buckets* aus dem Dashboard, oder wählen Sie *STORAGE (S3)* > *Buckets*.
+
Die Seite „Buckets“ wird angezeigt.

. Überprüfen Sie die Zusammenfassungsinformationen für jeden Bucket.
+
Bei Bedarf können Sie die Informationen nach einer beliebigen Spalte sortieren oder Sie können die Seite vorwärts und zurück durch die Liste blättern.

+

NOTE: Die angezeigten Werte für Objektanzahl und verwendeter Speicherplatz sind Schätzungen. Diese Schätzungen sind vom Zeitpunkt der Aufnahme, der Netzwerkverbindung und des Node-Status betroffen. Wenn Buckets die Versionierung aktiviert ist, sind gelöschte Objektversionen in der Objektanzahl enthalten.

+
[cols="1a,3a"]
|===
| Spalte | Beschreibung 


 a| 
Name
 a| 
Der eindeutige Name des Buckets, der nicht geändert werden kann.



 a| 
Aktivierte Funktionen
 a| 
Die Liste der Funktionen, die für den Bucket aktiviert sind.



 a| 
S3-Objektsperre
 a| 
Gibt an, ob S3 Object Lock für den Bucket aktiviert ist.

Diese Spalte wird nur angezeigt, wenn die S3-Objektsperre für das Raster aktiviert ist. In dieser Spalte werden außerdem Informationen für alle Buckets angezeigt, die für die Konformität mit älteren Daten verwendet wurden.



 a| 
Region
 a| 
Der Bereich des Eimers, der nicht geändert werden kann.



 a| 
Objektanzahl
 a| 
Die Anzahl der Objekte in diesem Bucket. Wenn Objekte hinzugefügt oder gelöscht werden, wird dieser Wert möglicherweise nicht sofort aktualisiert. Wenn für Buckets die Versionierung aktiviert ist, sind nicht aktuelle Objektversionen in diesem Wert enthalten.



 a| 
Belegten Speicherplatz
 a| 
Die logische Größe aller Objekte im Bucket Die logische Größe umfasst nicht den tatsächlich benötigten Speicherplatz für replizierte oder Erasure Coding-Kopien oder für Objekt-Metadaten.



 a| 
Erstellungsdatum
 a| 
Datum und Uhrzeit der Erstellung des Buckets.

|===
. Um Details für einen bestimmten Bucket anzuzeigen, wählen Sie den Bucket-Namen aus der Tabelle aus.
+
Die Seite mit den Bucket-Details wird angezeigt. Auf dieser Seite können Sie die folgenden Aufgaben ausführen, wenn Sie über die erforderlichen Berechtigungen verfügen:

+
** Konfiguration und Management von Bucket-Optionen:
+
*** link:ilm-policy-tags.html["ILM-Richtlinien-Tags"]
*** link:manage-bucket-consistency.html["Management der Bucket-Konsistenz"]
*** link:enabling-or-disabling-last-access-time-updates.html["Aktualisierung der Uhrzeit des letzten Zugriffs"]
*** link:changing-bucket-versioning.html["Objektversionierung"]
*** link:using-s3-object-lock.html["S3-Objektsperre"]
*** link:update-default-retention-settings.html["Standardmäßige Bucket-Aufbewahrung"]


** Konfigurieren Sie den Bucket-Zugriff, z. B. link:configuring-cross-origin-resource-sharing-cors.html["Cross-Origin Resource Sharing (CORS)"]
** link:what-platform-services-are.html["Management von Plattform-Services"] (Falls dem Mandanten gestattet), einschließlich CloudMirror-Replizierung, Ereignisbenachrichtigungen und Suchintegration
** Aktivieren Sie und link:grid-federation-manage-cross-grid-replication.html["Grid-übergreifende Replizierung managen"] (Falls dies für den Mandanten zulässig ist) zum Replizieren von Objekten, die in diesen Bucket aufgenommen wurden, auf ein anderes StorageGRID-System
** Auf das zugreifen link:use-s3-console.html["S3-Konsole"] Zum Verwalten der Objekte im Bucket
** link:deleting-s3-bucket-objects.html["Löschen aller Objekte in einem Bucket"]
** link:deleting-s3-bucket.html["Löschen eines Buckets"] Das ist bereits leer



