---
permalink: admin/adding-nfs-audit-client-to-audit-share.html 
sidebar: sidebar 
keywords: nfs, audit client, audit share 
summary: NFS-Audit-Clients erhalten auf Basis ihrer IP-Adresse Zugriff auf eine Revisionsfreigabe. Gewähren Sie einem neuen NFS-Audit-Client Zugriff auf die Revisionsfreigabe, indem Sie dessen IP-Adresse zur Revisionsfreigabe hinzufügen. 
---
= Fügen Sie einem Audit-Share einen NFS-Audit-Client hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS-Audit-Clients erhalten auf Basis ihrer IP-Adresse Zugriff auf eine Revisionsfreigabe. Gewähren Sie einem neuen NFS-Audit-Client Zugriff auf die Revisionsfreigabe, indem Sie dessen IP-Adresse zur Revisionsfreigabe hinzufügen.


NOTE: Die Unterstützung für NFS wurde veraltet und wird in einem zukünftigen Release entfernt.

.Bevor Sie beginnen
* Sie haben die `Passwords.txt` Datei mit dem Passwort für das Root-/Administratorkonto.
* Sie haben den `Configuration.txt` Datei (verfügbar im Wiederherstellungspaket).
* Der Audit-Client verwendet die NFS-Version 3 (NFSv3).


.Schritte
. Melden Sie sich beim primären Admin-Node an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_primary_Admin_Node_IP_`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
.. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
+
Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.



. Starten Sie das NFS-Konfigurationsprogramm: `config_nfs.rb`
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. Geben Sie Ein: `add-ip-to-share`
+
Es wird eine Liste der auf dem Admin-Knoten aktivierten NFS-Audit-Freigaben angezeigt. Die Revisionsfreigabe ist wie folgt aufgelistet: `/var/local/log`

. Geben Sie die Nummer der Revisionsfreigabe ein: `_audit_share_number_`
. Geben Sie bei entsprechender Aufforderung die IP-Adresse oder den IP-Adressbereich des Audit-Clients für die Revisionsfreigabe ein: `_client_IP_address_`
+
Der Audit-Client wird der Revisionsfreigabe hinzugefügt.

. Drücken Sie auf der entsprechenden Aufforderung *Enter*.
+
Das NFS-Konfigurationsprogramm wird angezeigt.

. Wiederholen Sie die Schritte für jeden Audit-Client, der zur Revisionsfreigabe hinzugefügt werden soll.
. Überprüfen Sie optional die Konfiguration: `validate-config`
+
Die Dienste werden überprüft und angezeigt.

+
.. Drücken Sie auf der entsprechenden Aufforderung *Enter*.
+
Das NFS-Konfigurationsprogramm wird angezeigt.



. Schließen Sie das NFS-Konfigurationsdienstprogramm: `exit`
. Wenn es sich bei der StorageGRID-Implementierung um einen einzelnen Standort handelt, mit dem nächsten Schritt fortfahren.
+
Wenn die StorageGRID-Bereitstellung Admin-Nodes an anderen Standorten umfasst, aktivieren Sie andernfalls optional diese Audit-Shares nach Bedarf:

+
.. Remote-Anmeldung beim Admin-Node eines Standorts:
+
... Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
... Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
... Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
... Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:


.. Wiederholen Sie diese Schritte, um die Revisionsfreigaben für jeden Admin-Knoten zu konfigurieren.
.. Schließen Sie die sichere Remote-Shell-Anmeldung am Remote-Admin-Node: `exit`


. Melden Sie sich aus der Befehlsshell ab: `exit`

