---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: Als Grid-Administrator erstellen und managen Sie die Mandantenkonten, die S3 und Swift-Clients zum Speichern und Abrufen von Objekten verwenden. 
---
= Mandanten managen: Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Als Grid-Administrator erstellen und managen Sie die Mandantenkonten, die S3 und Swift-Clients zum Speichern und Abrufen von Objekten verwenden.


NOTE: Die Unterstützung für Swift-Client-Anwendungen wurde veraltet und wird in einer zukünftigen Version entfernt.



== Was sind Mandantenkonten?

Ein Mandantenkonto ermöglicht Ihnen, entweder die Simple Storage Service (S3) REST-API oder die Swift REST-API zu verwenden, um Objekte in einem StorageGRID System zu speichern und abzurufen.

Jedes Mandantenkonto verfügt über föderierte oder lokale Gruppen, Benutzer, S3 Buckets oder Swift Container und Objekte.

Mandantenkonten können verwendet werden, um gespeicherte Objekte durch verschiedene Einheiten zu trennen. Beispielsweise können für einen der folgenden Anwendungsfälle mehrere Mandantenkonten verwendet werden:

* *Anwendungsbeispiel für Unternehmen:* Wenn Sie ein StorageGRID-System in einer Enterprise-Anwendung verwalten, sollten Sie den Objekt-Storage des Grid möglicherweise von den verschiedenen Abteilungen Ihres Unternehmens trennen. In diesem Fall können Sie Mandantenkonten für die Marketingabteilung, die Kundenbetreuung, die Personalabteilung usw. erstellen.
+

NOTE: Wenn Sie das S3-Client-Protokoll verwenden, können Sie S3-Buckets und Bucket-Richtlinien verwenden, um Objekte zwischen den Abteilungen eines Unternehmens zu trennen. Sie müssen keine Mandantenkonten verwenden. Siehe Anweisungen zur Implementierung link:../s3/bucket-and-group-access-policies.html["S3-Buckets und Bucket-Richtlinien"] Finden Sie weitere Informationen.

* *Anwendungsbeispiel Service Provider:* Wenn Sie ein StorageGRID-System als Service-Provider verwalten, können Sie den Objekt-Storage des Grid durch die verschiedenen Entitäten verteilen, die den Storage auf Ihrem Grid leasen. In diesem Fall würden Sie Mandantenkonten für Unternehmen A, Unternehmen B, Unternehmen C usw. erstellen.


Weitere Informationen finden Sie unter link:../tenant/index.html["Verwenden Sie ein Mandantenkonto"].



== Wie erstelle ich ein Mandantenkonto?

Wenn Sie ein Mandantenkonto erstellen, geben Sie die folgenden Informationen an:

* Grundlegende Informationen, einschließlich Mandantenname, Client-Typ (S3 oder Swift) und optionalem Storage-Kontingent.
* Berechtigungen für das Mandantenkonto, z. B. ob das Mandantenkonto S3-Plattformservices verwenden, seine eigene Identitätsquelle konfigurieren, S3 Select verwenden oder eine Grid-Verbundverbindung verwenden kann.
* Der erste Root-Zugriff für den Mandanten basiert darauf, ob das StorageGRID System lokale Gruppen und Benutzer, Identitätsföderation oder Single Sign On (SSO) verwendet.


Darüber hinaus können Sie die S3-Objektsperrung für das StorageGRID-System aktivieren, wenn S3-Mandantenkonten gesetzliche Vorgaben erfüllen müssen. Wenn S3 Object Lock aktiviert ist, können alle S3-Mandantenkonten konforme Buckets erstellen und managen.



== Wofür wird Tenant Manager verwendet?

Nachdem Sie das Mandantenkonto erstellt haben, können sich Mandantenbenutzer beim Tenant Manager anmelden, um Aufgaben wie die folgenden auszuführen:

* Identitätsföderation einrichten (es sei denn, die Identitätsquelle wird mit dem Grid gemeinsam genutzt)
* Verwalten von Gruppen und Benutzern
* Grid-Verbund für Account-Klone und Grid-übergreifende Replizierung verwenden
* Managen von S3-Zugriffsschlüsseln
* S3 Buckets erstellen und managen
* Verwenden Sie S3-Plattformservices
* Verwenden Sie S3 Select
* Monitoring der Storage-Auslastung



TIP: Benutzer von S3-Mandanten können mit dem Tenant Manager S3-Zugriffsschlüssel und -Buckets erstellen und managen, müssen jedoch Objekte mit einer S3-Client-Applikation aufnehmen und managen. Siehe link:../s3/index.html["S3-REST-API VERWENDEN"] Entsprechende Details.


TIP: Swift-Benutzer müssen über die Root-Zugriffsberechtigung für den Zugriff auf den Mandanten-Manager verfügen. Die Berechtigung Root-Zugriff erlaubt Benutzern jedoch nicht, sich in der Swift REST-API zu authentifizieren, um Container zu erstellen und Objekte aufzunehmen. Benutzer müssen über die Swift-Administratorberechtigung verfügen, um sich bei der Swift-REST-API zu authentifizieren.
