---
permalink: admin/verifying-nfs-audit-integration.html 
sidebar: sidebar 
keywords: nfs, audit share, audit client 
summary: Nachdem Sie eine Audit-Freigabe konfiguriert und einen NFS-Audit-Client hinzugefügt haben, können Sie die Audit-Client-Freigabe mounten und überprüfen, ob die Dateien über die Audit-Freigabe verfügbar sind. 
---
= Prüfung der NFS-Audit-Integration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie eine Audit-Freigabe konfiguriert und einen NFS-Audit-Client hinzugefügt haben, können Sie die Audit-Client-Freigabe mounten und überprüfen, ob die Dateien über die Audit-Freigabe verfügbar sind.


NOTE: Die Unterstützung für NFS wurde veraltet und wird in einem zukünftigen Release entfernt.

.Schritte
. Überprüfen Sie die Konnektivität (oder Variante für das Clientsystem) mithilfe der clientseitigen IP-Adresse des Admin-Knotens, der den AMS-Dienst hostet. Geben Sie Ein: `ping IP_address`
+
Stellen Sie sicher, dass der Server antwortet, und geben Sie die Konnektivität an.

. Mounten Sie die schreibgeschützte Revisionsfreigabe mit einem dem Client-Betriebssystem entsprechenden Befehl. Ein Beispiel für einen Linux-Befehl ist (geben Sie in einer Zeile ein):
+
`mount -t nfs -o hard,intr _Admin_Node_IP_address_:/var/local/log _myAudit_`

+
Verwenden Sie die IP-Adresse des Admin-Knotens, der den AMS-Dienst hostet, und den vordefinierten Freigabennamen für das Audit-System. Der Mount-Punkt kann ein beliebiger Name sein, der vom Client ausgewählt wurde (z. B. `_myAudit_` Im vorherigen Befehl).

. Stellen Sie sicher, dass die Dateien über die Revisionsfreigabe verfügbar sind. Geben Sie Ein: `ls _myAudit_ /*`
+
Wo `_myAudit_` Ist der Bereitstellungspunkt der Revisionsfreigabe. Es sollte mindestens eine Protokolldatei aufgeführt sein.


