---
permalink: maintain/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, installation files, download 
summary: Bevor Sie StorageGRID-Nodes wiederherstellen können, müssen Sie die Software herunterladen und die Dateien extrahieren. 
---
= Laden Sie StorageGRID-Installationsdateien herunter und extrahieren Sie sie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie StorageGRID-Nodes wiederherstellen können, müssen Sie die Software herunterladen und die Dateien extrahieren.

Sie müssen die Version von StorageGRID verwenden, die derzeit im Raster ausgeführt wird.

.Schritte
. Bestimmen Sie, welche Version der Software derzeit installiert ist. Wählen Sie oben im Grid Manager das Hilfesymbol aus und wählen Sie *über* aus.
. StorageGRID finden Sie auf der Seite zu NetApp Downloads.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^]

. Wählen Sie die Version von StorageGRID aus, die derzeit im Grid ausgeführt wird.
+
StorageGRID-Software-Versionen haben dieses Format: 11.x.y.

. Melden Sie sich mit Ihrem Benutzernamen und Passwort für Ihr NetApp Konto an.
. Lesen Sie die Endbenutzer-Lizenzvereinbarung, aktivieren Sie das Kontrollkästchen und wählen Sie dann *Akzeptieren und fortfahren* aus.
. Wählen Sie in der Spalte *Install StorageGRID* der Download-Seite die aus `.tgz` Oder `.zip` Datei für Ihre Plattform.
+
Die in der Archivdatei der Installation angezeigte Version muss mit der Version der derzeit installierten Software übereinstimmen.

+
Verwenden Sie die `.zip` Datei, wenn Sie Windows ausführen.

+
[cols="1a,2a"]
|===
| Plattform | Installationsarchiv 


 a| 
Red Hat Enterprise Linux
| `StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu oder Debian oder Appliances
| `StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz` 


 a| 
VMware
| `StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz` 
|===
. Laden Sie die Archivdatei herunter und extrahieren Sie sie.
. Befolgen Sie den entsprechenden Schritt für Ihre Plattform und wählen Sie die Dateien aus, die Sie benötigen, basierend auf Ihrer Plattform und den Grid-Nodes, die Sie wiederherstellen müssen.
+
Die im Schritt für jede Plattform aufgeführten Pfade beziehen sich auf das von der Archivdatei installierte Verzeichnis auf der obersten Ebene.

. Wenn Sie ein wiederherstellen link:../rhel/index.html["Red hat Enterprise Linux-System"], Wählen Sie die entsprechenden Dateien.


[cols="1a,1a"]
|===
| Pfad und Dateiname | Beschreibung 


| ./Effektivwert/README  a| 
Eine Textdatei, die alle in der StorageGRID-Download-Datei enthaltenen Dateien beschreibt.



| ./Effektivwert/NLF000000.txt  a| 
Eine kostenlose Lizenz, die keinen Support-Anspruch auf das Produkt bietet.



| ./Effektivwert/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
RPM-Paket für die Installation der StorageGRID-Node-Images auf Ihren RHEL-Hosts.



| ./Effektivwert/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
RPM-Paket für die Installation des StorageGRID-Hostdienstes auf Ihren RHEL-Hosts.



| Tool zur Implementierung von Skripten | Beschreibung 


| ./Effektivwert/configure-storagegrid.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration eines StorageGRID Systems.



| ./Effektivwert/configure-sga.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration von StorageGRID Appliances



| ./rpms/configure-storagegrid.sample.json  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript:



| ./Effektivwert/storagegrid-ssoauth.py  a| 
Ein Beispiel-Python-Skript, mit dem Sie sich bei aktivierter Single-Sign-On-Funktion bei der Grid-Management-API anmelden können. Sie können dieses Skript auch für Ping Federate verwenden.



| ./rpms/configure-storagegrid.blank.json  a| 
Eine leere Konfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript:



| ./rpms/Extras/ansible  a| 
Ansible-Beispielrolle und -Playbook zur Konfiguration von RHEL-Hosts für die Bereitstellung von StorageGRID-Containern. Die Rolle oder das Playbook können Sie nach Bedarf anpassen.



| ./eff/storagegrid-ssoauth-azure.py  a| 
Ein Beispiel für ein Python-Skript, mit dem Sie sich bei der Grid Management API anmelden können, wenn Single Sign-On (SSO) mithilfe von Active Directory oder Ping Federate aktiviert ist.



| ./RMS/storagegrid-ssoauth-Azure.js  a| 
Ein Hilfskript, das vom Begleiter aufgerufen wird `storagegrid-ssoauth-azure.py` Python-Skript zur Durchführung von SSO-Interaktionen mit Azure



| ./rpms/Extras/API-Schemata  a| 
API-Schemata für StorageGRID:

*Hinweis*: Bevor Sie ein Upgrade durchführen, können Sie diese Schemas verwenden, um zu bestätigen, dass jeder Code, den Sie zur Verwendung von StorageGRID Management APIs geschrieben haben, mit der neuen StorageGRID-Version kompatibel ist, wenn Sie keine StorageGRID-Umgebung außerhalb der Produktionsumgebung für Upgrade-Kompatibilitätstests haben.

|===
. Wenn Sie ein wiederherstellen link:../ubuntu/index.html["Ubuntu oder Debian-System"], Wählen Sie die entsprechenden Dateien.


[cols="1a,1a"]
|===
| Pfad und Dateiname | Beschreibung 


| ./DES/README  a| 
Eine Textdatei, die alle in der StorageGRID-Download-Datei enthaltenen Dateien beschreibt.



| ./Debs/NLF000000.txt  a| 
Eine NetApp Lizenzdatei, die nicht in der Produktionsumgebung enthalten ist und für Tests und Proof of Concept-Implementierungen genutzt werden kann



| ./Debs/storagegrid-webscale-images-version-SHA.deb  a| 
DEB-Paket zum Installieren der StorageGRID-Knoten-Images auf Ubuntu oder Debian-Hosts.



| ./Debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
MD5-Prüfsumme für die Datei `/debs/storagegrid-webscale-images-version-SHA.deb`.



| ./Debs/storagegrid-webscale-service-version-SHA.deb  a| 
DEB-Paket zur Installation des StorageGRID-Hostdienstes auf Ubuntu oder Debian-Hosts.



| Tool zur Implementierung von Skripten | Beschreibung 


| ./Debs/configure-storagegrid.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration eines StorageGRID Systems.



| ./Debs/configure-sga.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration von StorageGRID Appliances



| ./Debs/storagegrid-ssoauth.py  a| 
Ein Beispiel-Python-Skript, mit dem Sie sich bei aktivierter Single-Sign-On-Funktion bei der Grid-Management-API anmelden können. Sie können dieses Skript auch für Ping Federate verwenden.



| ./debs/configure-storagegrid.sample.json  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript:



| ./debs/configure-storagegrid.blank.json  a| 
Eine leere Konfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript:



| ./Debs/Extras/ansible  a| 
Beispiel-Rolle und Playbook für Ansible zur Konfiguration von Ubuntu oder Debian-Hosts für die Implementierung von StorageGRID-Containern Die Rolle oder das Playbook können Sie nach Bedarf anpassen.



| ./debs/storagegrid-ssoauth-azure.py  a| 
Ein Beispiel für ein Python-Skript, mit dem Sie sich bei der Grid Management API anmelden können, wenn Single Sign-On (SSO) mithilfe von Active Directory oder Ping Federate aktiviert ist.



| ./debs/storagegrid-ssoauth-Azure.js  a| 
Ein Hilfskript, das vom Begleiter aufgerufen wird `storagegrid-ssoauth-azure.py` Python-Skript zur Durchführung von SSO-Interaktionen mit Azure



| ./debs/Extras/API-Schemata  a| 
API-Schemata für StorageGRID:

*Hinweis*: Bevor Sie ein Upgrade durchführen, können Sie diese Schemas verwenden, um zu bestätigen, dass jeder Code, den Sie zur Verwendung von StorageGRID Management APIs geschrieben haben, mit der neuen StorageGRID-Version kompatibel ist, wenn Sie keine StorageGRID-Umgebung außerhalb der Produktionsumgebung für Upgrade-Kompatibilitätstests haben.

|===
. Wenn Sie ein wiederherstellen link:../vmware/index.html["VMware System"], Wählen Sie die entsprechenden Dateien.


[cols="1a,1a"]
|===
| Pfad und Dateiname | Beschreibung 


| ./vsphere/README  a| 
Eine Textdatei, die alle in der StorageGRID-Download-Datei enthaltenen Dateien beschreibt.



| ./vsphere/NLF000000.txt  a| 
Eine kostenlose Lizenz, die keinen Support-Anspruch auf das Produkt bietet.



| ./vsphere/NetApp-SG-Version-SHA.vmdk  a| 
Die Festplattendatei für Virtual Machines, die als Vorlage für die Erstellung von Grid-Node-Virtual Machines verwendet wird.



| ./vsphere/vsphere-primary-admin.ovf

./vsphere/vsphere-primary-admin.MF  a| 
Die Vorlagendatei „Open Virtualization Format“ (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung des primären Admin-Knotens.



| ./vsphere/vsphere-non-primary-admin.ovf

./vsphere/vsphere-non-primary-admin.MF  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung von nicht-primären Admin-Knoten.



| ./vsphere/vsphere-Archive.ovf

./vsphere/vsphere-Archive.MF  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung von Archiv-Knoten.



| ./vsphere/vsphere-Gateway.ovf

./vsphere/vsphere-Gateway.MF  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Für die Bereitstellung von Gateway-Knoten.



| ./vsphere/vsphere-Storage.ovf

./vsphere/vsphere-Storage.MF  a| 
Die Vorlagendatei (`.ovf`) Und Manifest-Datei (`.mf`) Zur Bereitstellung von virtuellen Maschinen-basierten Speicherknoten.



| Tool zur Implementierung von Skripten | Beschreibung 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Ein Bash Shell-Skript, das zur Automatisierung der Implementierung virtueller Grid-Nodes verwendet wird.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `deploy-vsphere-ovftool.sh` Skript:



| ./vsphere/configure-storagegrid.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration eines StorageGRID Systems.



| ./vsphere/configure-sga.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration von StorageGRID Appliances



| ./vsphere/storagegrid-ssoauth.py  a| 
Ein Beispiel für ein Python-Skript, mit dem Sie sich bei der Grid Management API anmelden können, wenn Single Sign-On (SSO) aktiviert ist. Sie können dieses Skript auch für Ping Federate verwenden.



| ./vsphere/configure-storagegrid.sample.json  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript:



| ./vsphere/configure-storagegrid.blank.json  a| 
Eine leere Konfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript:



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
Ein Beispiel für ein Python-Skript, mit dem Sie sich bei der Grid Management API anmelden können, wenn Single Sign-On (SSO) mithilfe von Active Directory oder Ping Federate aktiviert ist.



| ./vsphere/storagegrid-ssoauth-Azure.js  a| 
Ein Hilfskript, das vom Begleiter aufgerufen wird `storagegrid-ssoauth-azure.py` Python-Skript zur Durchführung von SSO-Interaktionen mit Azure



| ./vsphere/Extras/API-Schemata  a| 
API-Schemata für StorageGRID:

*Hinweis*: Bevor Sie ein Upgrade durchführen, können Sie diese Schemas verwenden, um zu bestätigen, dass jeder Code, den Sie zur Verwendung von StorageGRID Management APIs geschrieben haben, mit der neuen StorageGRID-Version kompatibel ist, wenn Sie keine StorageGRID-Umgebung außerhalb der Produktionsumgebung für Upgrade-Kompatibilitätstests haben.

|===
. Wenn Sie ein Appliance-basiertes StorageGRID-System wiederherstellen, wählen Sie die entsprechenden Dateien aus.


[cols="1a,1a"]
|===
| Pfad und Dateiname | Beschreibung 


| ./Debs/storagegrid-webscale-images-version-SHA.deb  a| 
DEB-Paket zum Installieren der StorageGRID Node Images auf den Geräten.



| ./Debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
MD5-Prüfsumme für die Datei `/debs/storagegridwebscale-
images-version-SHA.deb`.

|===

NOTE: Für die Installation der Appliance sind diese Dateien nur erforderlich, wenn Sie den Netzwerkverkehr vermeiden müssen. Die Appliance kann die erforderlichen Dateien vom primären Admin-Knoten herunterladen.
