---
permalink: maintain/grid-node-decommissioning.html 
sidebar: sidebar 
keywords: storagegrid, decommission, remove grid node 
summary: Mithilfe der Node-Deaktivierung können Sie einen oder mehrere Grid-Nodes an einem oder mehreren Standorten entfernen. Sie können den primären Admin-Node nicht stilllegen. 
---
= Deaktivierung von Grid Nodes: Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe der Node-Deaktivierung können Sie einen oder mehrere Grid-Nodes an einem oder mehreren Standorten entfernen. Der primäre Admin-Node kann nicht stillgelegt werden.



== Wann ein Node stillgelegt werden soll

Wenn einer der folgenden Optionen zutrifft, wird das Verfahren zur Deaktivierung des Nodes ausgeführt:

* Sie haben in einer Erweiterung einen größeren Storage Node hinzugefügt und möchten einen oder mehrere kleinere Storage Nodes entfernen, während gleichzeitig Objekte erhalten bleiben.
+

TIP: Wenn Sie ein älteres Gerät durch ein neueres Gerät ersetzen möchten, sollten Sie dies in Betracht ziehen https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["Klonen des Appliance-Node"^] Statt einer Erweiterung eine neue Appliance hinzuzufügen und die alte Appliance dann außer Betrieb zu setzen.

* Sie benötigen weniger Storage insgesamt.
* Sie benötigen keinen Gateway-Node mehr.
* Sie benötigen keinen nicht mehr primären Admin-Node.
* Das Raster enthält einen getrennten Knoten, den Sie nicht wiederherstellen oder wieder in den Online-Modus versetzen können.
* Ihr Raster enthält einen Archivknoten.




== Deaktivieren eines Node

Verbundene Grid-Nodes oder getrennte Grid-Nodes können deaktiviert werden.

Verbundene Nodes werden stillgelegt:: Im Allgemeinen sollten Sie Grid-Knoten nur dann stilllegen, wenn sie mit dem StorageGRID-System verbunden sind, und nur dann, wenn sich alle Knoten in einem normalen Zustand befinden (grüne Symbole auf den Seiten *NODES* und auf der Seite *Decommissionsknoten*).
+
--
Anweisungen hierzu finden Sie unter link:decommissioning-connected-grid-nodes.html["Verbundene Grid-Nodes ausmustern"].

--
Getrennte Nodes ausmustern:: In einigen Fällen müssen Sie möglicherweise einen Grid-Node außer Betrieb nehmen, der derzeit nicht mit dem Grid verbunden ist (einen Node, dessen Systemzustand Unbekannt oder Administrativ inaktiv ist). Sie können beispielsweise einen Archivknoten nur dekomprimieren, wenn er getrennt ist.
+
--
Anweisungen hierzu finden Sie unter link:decommissioning-disconnected-grid-nodes.html["Die getrennten Grid-Nodes werden deaktiviert"].

--




== Was vor der Stilllegung eines Knotens zu beachten ist

Bevor Sie eines der beiden Verfahren durchführen, sollten Sie die Überlegungen für jeden Node-Typ überprüfen:

* link:considerations-for-decommissioning-admin-or-gateway-nodes.html["Überlegungen für die Deaktivierung von Admin, Gateway oder Archive Node"]
* link:considerations-for-decommissioning-storage-nodes.html["Überlegungen zur Deaktivierung von Storage Node"]

