---
permalink: maintain/grid-node-recovery-procedures.html 
sidebar: sidebar 
keywords: storagegrid, recovery 
summary: Wenn ein Grid-Node ausfällt, können Sie ihn wiederherstellen, indem Sie den fehlerhaften physischen oder virtuellen Server ersetzen, die StorageGRID Software neu installieren und wiederherstellbare Daten wiederherstellen. 
---
= Verfahren zur Wiederherstellung von Grid Nodes: Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Grid-Node ausfällt, können Sie ihn wiederherstellen, indem Sie den fehlerhaften physischen oder virtuellen Server ersetzen, die StorageGRID Software neu installieren und wiederherstellbare Daten wiederherstellen.

Grid Nodes können ausfallen, wenn ein Hardware-, Virtualisierungs-, Betriebssystem- oder Softwarefehler den Node funktionsunfähig oder unzuverlässig macht. Es gibt viele Arten von Fehlern, die die Notwendigkeit zur Wiederherstellung eines Grid-Node auslösen können.

Die Schritte zur Wiederherstellung eines Grid-Node sind abhängig von der Plattform, auf der der der Grid-Node gehostet wird, und vom Typ des Grid-Nodes. Jeder Grid-Node-Typ verfügt über eine bestimmte Recovery-Prozedur, die Sie genau befolgen müssen.

Im Allgemeinen versuchen Sie, soweit möglich Daten vom ausgefallenen Grid Node aufzubewahren, reparieren oder ersetzen den ausgefallenen Node, verwenden den Grid Manager zum Konfigurieren des Ersatz-Node und stellen die Daten des Node wieder her.


NOTE: Wenn eine gesamte StorageGRID Site ausfällt, wenden Sie sich an den technischen Support. Der technische Support arbeitet mit Ihnen zusammen an der Entwicklung und Umsetzung eines Site Recovery-Plans, der die wiederherzustellenden Datenmenge maximiert und Ihre Geschäftsziele erreicht. Siehe link:how-site-recovery-is-performed-by-technical-support.html["Wie der technische Support eine Site wiederherstellt"].
