---
permalink: maintain/modifying-dns-configuration-for-single-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, dns, modify dns 
summary: Anstatt den DNS global für die gesamte Bereitstellung zu konfigurieren, können Sie ein Skript ausführen, um DNS für jeden Grid-Knoten anders zu konfigurieren. 
---
= Ändern der DNS-Konfiguration für einen einzelnen Grid-Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Anstatt den DNS global für die gesamte Bereitstellung zu konfigurieren, können Sie ein Skript ausführen, um DNS für jeden Grid-Knoten anders zu konfigurieren.

Im Allgemeinen sollten Sie die Option *MAINTENANCE* > *Network* > *DNS Servers* im Grid Manager verwenden, um DNS-Server zu konfigurieren. Verwenden Sie das folgende Skript nur, wenn Sie unterschiedliche DNS-Server für unterschiedliche Grid-Nodes verwenden müssen.

.Schritte
. Melden Sie sich beim primären Admin-Node an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_primary_Admin_Node_IP_`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
.. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
+
Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.

.. Fügen Sie den SSH-privaten Schlüssel zum SSH-Agenten hinzu. Geben Sie Ein: `ssh-add`
.. Geben Sie das SSH-Zugriffspasswort ein, das im aufgeführt ist `Passwords.txt` Datei:


. [[log_in_to_Node]]Melden Sie sich beim Knoten an, den Sie mit einer benutzerdefinierten DNS-Konfiguration aktualisieren möchten: `ssh _node_IP_address_`
. Führen Sie das DNS-Setup-Skript aus: `setup_resolv.rb.`
+
Das Skript antwortet mit der Liste der unterstützten Befehle.

+
[listing]
----
Tool to modify external name servers

available commands:
  add search <domain>
               add a specified domain to search list
               e.g.> add search netapp.com
  remove search <domain>
               remove a specified domain from list
               e.g.> remove search netapp.com
  add nameserver <ip>
               add a specified IP address to the name server list
               e.g.> add nameserver 192.0.2.65
  remove nameserver <ip>
               remove a specified IP address from list
               e.g.> remove nameserver 192.0.2.65
  remove nameserver all
               remove all nameservers from list
  save         write configuration to disk and quit
  abort        quit without saving changes
  help         display this help message


Current list of name servers:
    192.0.2.64
Name servers inherited from global DNS configuration:
    192.0.2.126
    192.0.2.127
Current list of search entries:
    netapp.com

Enter command [`add search <domain>|remove search <domain>|add nameserver <ip>`]
              [`remove nameserver <ip>|remove nameserver all|save|abort|help`]
----
. Fügen Sie die IPv4-Adresse eines Servers hinzu, der einen Domänennamendienst für Ihr Netzwerk bereitstellt: `add <nameserver IP_address>`
. Wiederholen Sie den `add nameserver` Befehl zum Hinzufügen von Nameserver.
. Befolgen Sie die Anweisungen, wenn Sie dazu aufgefordert werden, weitere Befehle einzugeben.
. Speichern Sie Ihre Änderungen und beenden Sie die Anwendung: `save`
. [[close_cmd_Shell]]Schließen Sie die Befehlsshell auf dem Server: `exit`
. Wiederholen Sie für jeden Grid-Node die Schritte von <<log_in_to_node,Anmeldung beim Node>> Bis <<close_cmd_shell,Schließen der Befehlsshell>>.
. Wenn Sie keinen passwortlosen Zugriff auf andere Server mehr benötigen, entfernen Sie den privaten Schlüssel vom SSH-Agent. Geben Sie Ein: `ssh-add -D`

