---
permalink: maintain/viewing-server-manager-status-and-version.html 
sidebar: sidebar 
keywords: storagegrid, recover, server manager, status, version 
summary: Für jeden Grid-Node können Sie den aktuellen Status und die Version des auf diesem Grid-Node ausgeführten Server Managers anzeigen. Zudem erhalten Sie den aktuellen Status aller auf diesem Grid-Node ausgeführten Services. 
---
= Zeigen Sie den Status und die Version von Server Manager an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für jeden Grid-Node können Sie den aktuellen Status und die Version des auf diesem Grid-Node ausgeführten Server Managers anzeigen. Zudem erhalten Sie den aktuellen Status aller auf diesem Grid-Node ausgeführten Services.

.Bevor Sie beginnen
Sie haben die `Passwords.txt` Datei:

.Schritte
. Melden Sie sich beim Grid-Node an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
.. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:


+
Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.

. Anzeigen des aktuellen Status von Server Manager, der auf dem Grid-Node ausgeführt wird: `*service servermanager status*`
+
Der aktuelle Status von Server Manager, der auf dem Grid-Knoten ausgeführt wird, wird gemeldet (wird ausgeführt oder nicht). Wenn der Status von Server Manager lautet `running`, Die Zeit, die es seit dem letzten Start läuft, ist aufgelistet. Beispiel:

+
[listing]
----
servermanager running for 1d, 13h, 0m, 30s
----
. Zeigen Sie die aktuelle Version von Server Manager an, der auf einem Grid-Node ausgeführt wird: `*service servermanager version*`
+
Die aktuelle Version wird aufgelistet. Beispiel:

+
[listing]
----
11.1.0-20180425.1905.39c9493
----
. Melden Sie sich aus der Befehlsshell ab: `*exit*`

