---
permalink: maintain/whats-next-performing-additional-recovery-steps-if-required.html 
sidebar: sidebar 
keywords: storagegrid, recover, corrective action, additional recovery 
summary: Abhängig von den spezifischen Aktionen, die Sie unternommen haben, um die StorageGRID Nodes auf dem Ersatzhost auszuführen, müssen Sie möglicherweise zusätzliche Recovery-Schritte für jeden Node durchführen. 
---
= Was ist weiter: Führen Sie zusätzliche Recovery-Schritte, wenn erforderlich
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Abhängig von den spezifischen Aktionen, die Sie unternommen haben, um die StorageGRID Nodes auf dem Ersatzhost auszuführen, müssen Sie möglicherweise zusätzliche Recovery-Schritte für jeden Node durchführen.

Die Node-Recovery ist abgeschlossen, wenn Sie keine Korrekturmaßnahmen vornehmen müssen, während Sie den Linux Host ersetzt oder den ausgefallenen Grid Node auf dem neuen Host wiederhergestellt haben.



== Korrekturmaßnahmen und nächste Schritte

Während des Austauschs von Nodes müssen Sie möglicherweise eine der folgenden Korrekturmaßnahmen ergreifen:

* Man musste das benutzen `--force` Flag zum Importieren des Knotens.
* Für alle `<PURPOSE>`, Der Wert des `BLOCK_DEVICE_<PURPOSE>` Die Variable der Konfigurationsdatei bezieht sich auf ein Blockgerät, das nicht die gleichen Daten enthält, die es vor dem Ausfall des Hosts gemacht hat.
* Sie sind ausgestellt `storagegrid node force-recovery _node-name_` Für den Node.
* Sie haben ein neues Blockgerät hinzugefügt.


Wenn Sie *eine* dieser Korrekturmaßnahmen ergriffen haben, müssen Sie zusätzliche Wiederherstellungsschritte durchführen.

[cols="2a,1a"]
|===
| Art der Wiederherstellung | Nächster Schritt 


 a| 
Primärer Admin-Node
 a| 
link:configuring-replacement-primary-admin-node.html["Primären Ersatzadministrator-Knoten konfigurieren"]



 a| 
Nicht primärer Admin-Node
 a| 
link:selecting-start-recovery-to-configure-non-primary-admin-node.html["Wählen Sie Wiederherstellung starten, um einen nicht-primären Admin-Node zu konfigurieren"]



 a| 
Gateway-Node
 a| 
link:selecting-start-recovery-to-configure-gateway-node.html["Wählen Sie Wiederherstellung starten, um Gateway-Node zu konfigurieren"]



 a| 
Archiv-Node
 a| 
link:selecting-start-recovery-to-configure-archive-node.html["Wählen Sie Wiederherstellung starten, um den Knoten Archiv zu konfigurieren"]



 a| 
Storage-Node (softwarebasiert):

* Wenn man das benutzen musste `--force` Flag, um den Knoten zu importieren, oder Sie haben ausgegeben `storagegrid node force-recovery _node-name_`
* Wenn Sie eine vollständige Neuinstallation des Knotens durchführen mussten, oder Sie müssen /var/local wiederherstellen

 a| 
link:selecting-start-recovery-to-configure-storage-node.html["Wählen Sie Wiederherstellung starten, um Speicherknoten zu konfigurieren"]



 a| 
Storage-Node (softwarebasiert):

* Wenn Sie ein neues Blockgerät hinzugefügt haben.
* Wenn, für alle `<PURPOSE>`, Der Wert des `BLOCK_DEVICE_<PURPOSE>` Die Variable der Konfigurationsdatei bezieht sich auf ein Blockgerät, das nicht die gleichen Daten enthält, die es vor dem Ausfall des Hosts gemacht hat.

 a| 
link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["Wiederherstellung nach einem Storage-Volume-Ausfall bei intaktem Systemlaufwerk"]

|===