---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: Storage-Nodes managen und speichern Objektdaten und Metadaten. Storage-Nodes umfassen die Services und Prozesse, die zum Speichern, Verschieben, Überprüfen und Abrufen von Objektdaten und Metadaten auf der Festplatte erforderlich sind. 
---
= Was ist ein Storage-Node?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage-Nodes managen und speichern Objektdaten und Metadaten. Storage-Nodes umfassen die Services und Prozesse, die zum Speichern, Verschieben, Überprüfen und Abrufen von Objektdaten und Metadaten auf der Festplatte erforderlich sind.

Jeder Standort im StorageGRID-System muss über mindestens drei Storage-Nodes verfügen.



== Typen von Storage-Nodes

Alle Storage-Nodes, die vor StorageGRID 11.8 installiert wurden, speichern sowohl Objekte als auch Metadaten für diese Objekte. Ab StorageGRID 11.8 können Sie den Speicher-Node-Typ für neue softwarebasierte Speicher-Nodes auswählen:

Objekt- und Metadaten-Storage-Nodes:: Standardmäßig speichern alle neuen Speicher-Nodes, die in StorageGRID 11.8 installiert sind, sowohl Objekte als auch Metadaten.
Nur Metadaten Storage-Nodes (nur softwarebasierte Nodes):: Sie können angeben, dass ein neuer softwarebasierter Storage-Node nur zum Speichern von Metadaten verwendet wird. Während der StorageGRID Systemerweiterung können Sie dem StorageGRID System auch einen rein metadatenbasierten softwarebasierten Storage-Node hinzufügen.
+
--

NOTE: Sie können den Storage-Node-Typ nur auswählen, wenn Sie den softwarebasierten Node zu Beginn installieren oder den softwarebasierten Node während der StorageGRID-Systemerweiterung installieren. Sie können den Typ nicht ändern, nachdem die Node-Installation abgeschlossen ist.

--


Die Installation eines Node, der nur Metadaten enthält, ist in der Regel nicht erforderlich. Die ausschließliche Verwendung eines Storage-Nodes für Metadaten kann jedoch sinnvoll sein, wenn Ihr Grid eine sehr große Anzahl kleiner Objekte speichert. Die Installation von dedizierten Metadaten sorgt für ein besseres Gleichgewicht zwischen dem für eine sehr große Anzahl an kleinen Objekten erforderlichen Speicherplatz und dem für alle Metadaten erforderlichen Speicherplatz.

Die Node-Ressourcen, die nur auf Softwarebasierten Metadaten basieren, müssen mit den vorhandenen Storage-Nodes-Ressourcen übereinstimmen. Beispiel:

* Wenn der bestehende StorageGRID Standort SG6000 oder SG6100 Appliances verwendet, müssen die rein softwarebasierten Nodes mit Metadaten die folgenden Mindestanforderungen erfüllen:
+
** 128 GB RAM
** 8-Core-CPU
** 8 TB SSD oder äquivalenter Storage für die Cassandra-Datenbank (rangedb/0)


* Wenn der bestehende StorageGRID-Standort virtuelle Storage-Nodes mit 24 GB RAM, 8 Kern-CPUs und 3 TB oder 4 TB Metadaten-Storage verwendet, sollten die rein softwarebasierten Metadaten-Nodes ähnliche Ressourcen verwenden (24 GB RAM, 8 Kern-CPU und 4 TB Metadaten-Storage (rangedb/0).


Beim Hinzufügen eines neuen StorageGRID Standorts sollte die Metadaten-Gesamtkapazität des neuen Standorts mindestens den vorhandenen StorageGRID Standorten entsprechen, und neue Standortressourcen sollten den Storage-Nodes an den vorhandenen StorageGRID Standorten entsprechen.

Bei der Installation eines Grid mit softwarebasierten, metadatenbasierten Nodes muss das Grid auch eine Mindestanzahl an Nodes für Objekt-Storage enthalten:

* Für ein Grid an einem Standort werden mindestens zwei Storage-Nodes für Objekte und Metadaten konfiguriert.
* Bei einem Grid mit mehreren Standorten werden mindestens ein Storage Node pro Standort für Objekte und Metadaten konfiguriert.


Softwarebasierte Storage-Nodes zeigen auf allen Seiten, auf denen der Storage-Node-Typ aufgeführt ist, eine nur-Metadaten-Anzeige für jeden nur-Metadaten-Node an.



== Primäre Services für Storage-Nodes

Die folgende Tabelle enthält die primären Services für Storage-Nodes. In dieser Tabelle werden jedoch nicht alle Node-Services aufgeführt.


NOTE: Einige Services, wie z. B. der ADC-Service und der RSM-Service, bestehen in der Regel nur auf drei Storage-Nodes an jedem Standort.

[cols="1a,3a"]
|===
| Service | Tastenfunktion 


 a| 
Konto (Konto)
 a| 
Management von Mandantenkonten.



 a| 
Administrativer Domänen-Controller (ADC)
 a| 
Aufrechterhaltung der Topologie und Grid-Konfiguration

.Details
[%collapsible]
====
Der Dienst Administrative Domain Controller (ADC) authentifiziert Grid-Knoten und ihre Verbindungen miteinander. Der ADC-Dienst wird auf mindestens drei Storage Nodes an einem Standort gehostet.

Der ADC-Dienst verwaltet Topologiedaten, einschließlich Standort und Verfügbarkeit von Diensten. Wenn ein Grid-Knoten Informationen von einem anderen Grid-Knoten benötigt oder eine Aktion von einem anderen Grid-Knoten ausgeführt werden muss, kontaktiert er einen ADC-Service, um den besten Grid-Knoten für die Bearbeitung seiner Anforderung zu finden. Darüber hinaus behält der ADC-Service eine Kopie der Konfigurationspakete der StorageGRID-Bereitstellung bei, sodass jeder Grid-Node aktuelle Konfigurationsinformationen abrufen kann.

Zur Erleichterung von verteilten und isanded-Operationen synchronisiert jeder ADC-Dienst Zertifikate, Konfigurationspakete und Informationen über Services und Topologie mit den anderen ADC-Diensten im StorageGRID-System.

Im Allgemeinen unterhalten alle Rasterknoten eine Verbindung zu mindestens einem ADC-Dienst. So wird sichergestellt, dass die Grid-Nodes immer auf die neuesten Informationen zugreifen. Wenn sich Grid-Nodes verbinden, werden die Zertifikate anderer Grid-Nodes zwischengespeichert, sodass die Systeme mit bekannten Grid-Nodes weiterarbeiten können, selbst wenn ein ADC-Dienst nicht verfügbar ist. Neue Grid-Knoten können nur Verbindungen über einen ADC-Dienst herstellen.

Durch die Verbindung jedes Grid-Knotens kann der ADC-Service Topologiedaten erfassen. Die Informationen zu diesem Grid-Node umfassen die CPU-Last, den verfügbaren Festplattenspeicher (wenn der Storage vorhanden ist), unterstützte Services und die Standort-ID des Grid-Node. Andere Dienste fragen den ADC-Service nach Topologiedaten durch Topologieabfragen. Der ADC-Dienst reagiert auf jede Abfrage mit den neuesten Informationen, die vom StorageGRID-System empfangen wurden.

====


 a| 
Cassandra
 a| 
Speichert und sichert Objekt-Metadaten.



 a| 
Cassandra Reaper
 a| 
Führt automatische Reparaturen von Objektmetadaten durch.



 a| 
Chunk
 a| 
Verwaltet Erasure-codierte Daten und Paritätsfragmente.



 a| 
Data Mover (dmv)
 a| 
Verschiebt Daten in Cloud-Storage-Pools



 a| 
Verteilter Datenspeicher (DDS)
 a| 
Überwacht Objekt-Metadaten-Storage

.Details
[%collapsible]
====
Jeder Storage Node umfasst den Distributed Data Store (DDS)-Service. Dieser Service ist mit der Cassandra-Datenbank verbunden, um Hintergrundaufgaben für die im StorageGRID-System gespeicherten Objektmetadaten auszuführen.

Der DDS-Dienst verfolgt die Gesamtzahl der im StorageGRID-System aufgenommenen Objekte sowie die Gesamtzahl der über die unterstützten Schnittstellen (S3 oder Swift) des Systems aufgenommenen Objekte.

====


 a| 
Identität (idnt)
 a| 
Föderiert Benutzeridentitäten von LDAP und Active Directory



 a| 
LDR (Local Distribution Router)
 a| 
Verarbeitet Protokollanfragen von Objekt-Storage und managt Objektdaten auf der Festplatte.

.Details
[%collapsible]
====
Jeder Storage Node enthält den Local Distribution Router (LDR)-Service. Dieser Service übernimmt Funktionen für den Content-Transport, einschließlich Datenspeicherung, Routing und Bearbeitung von Anfragen. Der LDR-Dienst erledigt die meiste harte Arbeit des StorageGRID-Systems durch die Verarbeitung von Datenübertragungslasten und Datenverkehrsfunktionen.

Der LDR-Service übernimmt folgende Aufgaben:

* Abfragen
* Information Lifecycle Management-Aktivitäten (ILM
* Löschen von Objekten
* Objekt-Storage
* Objektdatenübertragung von einem anderen LDR-Service (Storage Node)
* Datenspeicher-Management
* Protokollschnittstellen (S3 und Swift)


Der LDR-Service ordnet außerdem jedem S3- und Swift-Objekt seine eindeutige UUID zu.

Objektspeicher:: Der zugrunde liegende Datenspeicher eines LDR-Service wird in eine feste Anzahl an Objektspeichern (auch Storage-Volumes genannt) unterteilt. Jeder Objektspeicher ist ein separater Bereitstellungspunkt.
+
--
Das Objekt speichert in einem Storage-Node werden durch eine Hexadezimalzahl zwischen 0000 und 002F identifiziert, die als Volume-ID bezeichnet wird. Der Speicherplatz ist im ersten Objektspeicher (Volume 0) für Objekt-Metadaten in einer Cassandra-Datenbank reserviert. Für Objektdaten werden alle verbleibenden Speicherplatz auf diesem Volume verwendet. Alle anderen Objektspeichern werden ausschließlich für Objektdaten verwendet, zu denen replizierte Kopien und nach dem Erasure-Coding-Verfahren Fragmente gehören.

Um sicherzustellen, dass selbst der Speicherplatz für replizierte Kopien genutzt wird, werden Objektdaten für ein bestimmtes Objekt auf Basis des verfügbaren Storage in einem Objektspeicher gespeichert. Wenn ein Objektspeicher voll ist, speichern die übrigen Objektspeicher weiterhin Objekte, bis kein Speicherplatz mehr auf dem Storage-Node vorhanden ist.

--
Metadatensicherung:: StorageGRID speichert Objekt-Metadaten in einer Cassandra-Datenbank, die über eine Schnittstelle zum LDR-Service verfügt.
+
--
Um Redundanz sicherzustellen und so vor Verlust zu schützen, werden an jedem Standort drei Kopien von Objekt-Metadaten aufbewahrt. Diese Replikation ist nicht konfigurierbar und wird automatisch ausgeführt. Weitere Informationen finden Sie unter link:../admin/managing-object-metadata-storage.html["Management von Objekt-Metadaten-Storage"].

--


====


 a| 
Replicated State Machine (RSM)
 a| 
Stellt sicher, dass Serviceanfragen der S3-Plattform an ihre jeweiligen Endpunkte gesendet werden.



 a| 
Server Status Monitor (SSM)
 a| 
Überwachung des Betriebssystems und der zugrunde liegenden Hardware

|===